#!/usr/bin/env bash

BILLINGPATH=/root/billing/billing
INSTPATH=/usr/local/lib/python2.7/site-packages/

echo "Removing obsolete files..."
rm $INSTPATH/rules.py
rm -rf $INSTPATH/billing $INSTPATH/accounts $INSTPATH/longer_username $INSTPATH/packages

echo "Copying new files to site-packages..."
cp rules.py $INSTPATH
cp -r $BILLINGPATH/billing $BILLINGPATH/accounts $BILLINGPATH/longer_username $BILLINGPATH/packages $INSTPATH

echo "Deployment done"
